### ISSUE TITLE
Option to use git branch name automatically as alias

### ISSUE THREAD

**Issue by HyperBrain** [HyperBrain/serverless-aws-alias#10]
# Feature request

The alias plugin is especially valuable for development in a multi-developer scenario with features developed in separate branches. An idea is that the plugin offers an option (either in serverless.yml or as a commandline parameter) that automatically derives the alias name from the branch that is deployed from.

If enabled the plugin would use git to determine the current branch. Then it would automatically set the alias name to the branch name on "serverless deploy".

The exception are builds done on build servers, where in general a commit is checked out and not a special branch. The plugin should determine this scenario and refuse deployment on such systems without specifying an explicit alias (via the --alias switch).

**Comment by arabold** [comment]
As we use one branch per feature and per bug, we have A LOT of branches over the course of a few weeks. This feature would require a cleanup of these branches once merged into master but I'm not sure how this should work on a CI/CD.

**Comment by HyperBrain** [comment]
Yes, you're right. This is probably not a feature that would be used in such a heavy load environment (in regards to code creation and death). Maybe on the developer side the already existing `deploy --alias` and `remove alias --alias` workflows are pretty enough to let devs test their implementation and keep control over the lifetime of an alias by themselves.
Another issue with the branch name approach could be the length limits for stack names that are implied by AWS (max. 128 characters). Structured git branch names would easily break here.

**Comment by HyperBrain** [comment]
Closing this for now as it is quite exotic and error-prone.
