### ISSUE TITLE
Next release?

### ISSUE THREAD

**Issue by daniel-cottone** [HyperBrain/serverless-aws-alias#103]
When can we expect a new release? There are a few bugfixes that have been merged that we'd like to start using.

**Comment by HyperBrain** [comment]
As soon as I reviewed #102 , then the next version is complete. Expect the release to happen this week.

**Comment by daniel-cottone** [comment]
Any update on this?

**Comment by HyperBrain** [comment]
@daniel-cottone Oh, sorry. Will do it NOW :)

**Comment by HyperBrain** [comment]
[1.6.0](https://github.com/HyperBrain/serverless-aws-alias/releases/tag/v1.6.0) available on npm

**Comment by HyperBrain** [comment]
Will release 1.6.1 in a few minutes ... Closing this now.
