### ISSUE TITLE
Add preconfigured sample service

### ISSUE THREAD

**Issue by HyperBrain** [HyperBrain/serverless-aws-alias#11]
## The sample service mentioned in the README should be made available.

As it should show how the plugin behaves with different configurations, it has to be offered as a separate GitHub repository rather than within a subfolder.
The sample respository will have different branches set up, that simulate real development and can just be deployed from the branches after it has been cloned.

**Comment by HyperBrain** [comment]
Example project available here: https://github.com/HyperBrain/serverless-aws-alias-example

**Comment by mikelax** [comment]
👍 
one question, do you want to update the README to point to the new repo for the sample project(s)?

**Comment by HyperBrain** [comment]
Good idea 😄 I just missed that.

**Comment by HyperBrain** [comment]
Just pushed a new README to master. If there are any issues with the sample project, please let me know (as issue in the sample repo)
