### ISSUE TITLE
Add alias information to serverless info command

### ISSUE THREAD

**Issue by HyperBrain** [HyperBrain/serverless-aws-alias#2]
`serverless alias` should show a list of deployed aliases.

This is helpful if you want to get an overview or want to remove aliases that are not needed anymore and consume resources for nothing.

**Comment by arabold** [comment]
I suggest to make this part of the built-in `serverless info` command instead.

**Comment by HyperBrain** [comment]
I can try to do that (if hooks are available in that area)

**Comment by HyperBrain** [comment]
Currently the APIG deployed stage details cannot be shown. It seems that there is a bug in AWS::APIGateway::getDeployment() that prevents the return of the apiSummary object, which we need here. As soon as they've fixed the issue the functionality can be enabled again.

**Comment by HyperBrain** [comment]
Due to the AWS issue mentioned in the comment above I created a separate task for the APIG information.
See Issue #3 So this one can be closed.
