### ISSUE TITLE
Use stage variables to specify lambda qualifier in APIG

### ISSUE THREAD

**Issue by vkkis93** [HyperBrain/serverless-aws-alias#40]
On  Integration request page  field **lambda function** always has value of last deployed stage.
For Example
getUser:staging or getUser:production.
I think it should be like getUser:${functionAlias}
Where functionAlias value should be specified in stage variables tab

**Comment by HyperBrain** [comment]
Good point, thank you. I will investigate the issue.

**Comment by HyperBrain** [comment]
I set a stage variable SERVERLESS_ALIAS that equals the deployed stage, so if I would set it to getUser:${SERVERLESS_ALIAS} it should work.
Then you could specify that explicitly for testing.

Nevertheless, the deployed stages should call the aliased functions correctly. It is only an issue with the AWS ApiGateway testing console.

**Comment by HyperBrain** [comment]
@vkkis93 This was indeed a great idea 🙌 I changed the qualifier/alias to the stage variable and tested it with two different aliases. It would be good, if you also give it a try with the alias plugin master branch.

**Comment by vkkis93** [comment]
@HyperBrain brilliant work.
Thank you.

**Comment by vkkis93** [comment]
@HyperBrain Can you create new npm package with this fix?

**Comment by HyperBrain** [comment]
I will publish the fix in a few moments.
