### ISSUE TITLE
Use stage variables to specify authorizer lambda function in APIG

### ISSUE THREAD

**Issue by vkkis93** [HyperBrain/serverless-aws-alias#44]
Hello,
The problem the same like here https://github.com/HyperBrain/serverless-aws-alias/issues/40
In APIG in Authorizers Lambda function should be ${functionName}:${stageVariables.SERVERLESS_ALIAS}
Can you do something with that?

**Comment by vkkis93** [comment]
Looks like it's my problem https://github.com/HyperBrain/serverless-aws-alias/issues/22 ?

**Comment by HyperBrain** [comment]
Yes it is. I will schedule authorizer support for the next release. Closing this as duplicate.
