### ISSUE TITLE
Cannot read property 'Fn::Join' of undefined when specifying a User Pools authorizer

### ISSUE THREAD

**Issue by SeptiyanAndika** [HyperBrain/serverless-aws-alias#51]
Attempting to deploy  i get error ` Cannot read property 'Fn::Join' of undefined`, this is the logs terminals.

> Serverless: Packaging service...
> Serverless: Preparing alias ...
>  
>   Type Error ---------------------------------------------
>  
>      Cannot read property 'Fn::Join' of undefined
>  
>      For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
>  
>   Get Support --------------------------------------------
>      Docs:          docs.serverless.com
>      Bugs:          github.com/serverless/serverless/issues
>      Forums:        forum.serverless.com
>      Chat:          gitter.im/serverless/serverless
>  
>   Your Environment Information -----------------------------
>      OS:                 darwin
>      Node Version:       6.9.1
>      Serverless Version: 1.14.0

can you help me, thanks?

**Comment by HyperBrain** [comment]
Can you provide more details on your serverless.yml or your service configuration?
I assume that this is a bug that is restricted to a specific resource type or trigger.

**Comment by SeptiyanAndika** [comment]
this is my serverless.yml
`# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: users

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: nodejs6.10

# you can overwrite defaults here
  stage: dev
  region: us-west-2
  profile: xxxxx

# you can add statements to the Lambda function's IAM Role here
#  iamRoleStatements:
#    - Effect: "Allow"
#      Action:
#        - "s3:ListBucket"
#      Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ] ]  }
#    - Effect: "Allow"
#      Action:
#        - "s3:PutObject"
#      Resource:
#        Fn::Join:
#          - ""
#          - - "arn:aws:s3:::"
#            - "Ref" : "ServerlessDeploymentBucket"
#            - "/*"

# you can define service wide environment variables here
#  environment:
#    variable1: value1

# you can add packaging information here
#package:
#  include:
#    - include-me.js
#    - include-me-dir/**
#  exclude:
#    - exclude-me.js
#    - exclude-me-dir/**

functions:
  authAdmin:
    handler: authorizer.custom
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
          authorizer:
            arn: arn:aws:cognito-idp:us-west-2:XXXXXX:userpool/XXXXXXXX
  helloAdmin:
    handler: handler.helloAdmin
    events:
      - http:
          path: admin
          method: post
          authorizer:
            name: authAdmin    

#    The following are a few example events you can configure
#    NOTE: Please make sure to change your handler code to work with those events
#    Check the event documentation for details
#    events:
#      - http:
#          path: users/create
#          method: get
#      - s3: ${env:BUCKET}
#      - schedule: rate(10 minutes)
#      - sns: greeter-topic
#      - stream: arn:aws:dynamodb:region:XXXXXX:table/foo/stream/1970-01-01T00:00:00.000
#      - alexaSkill
#      - iot:
#          sql: "SELECT * FROM 'some_topic'"
#      - cloudwatchEvent:
#          event:
#            source:
#              - "aws.ec2"
#            detail-type:
#              - "EC2 Instance State-change Notification"
#            detail:
#              state:
#                - pending
#      - cloudwatchLog: '/aws/lambda/hello'

#    Define function environment variables here
#    environment:
#      variable2: value2

# you can add CloudFormation resource templates here
#resources:
#  Resources:
#    NewResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: my-new-bucket
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
plugins:
  - serverless-offline
  - serverless-aws-alias
`

**Comment by HyperBrain** [comment]
Many thanks for the information 🙌 . I'm sure it has anything to do with the authorizer declarations. I will look into the issue soon.

**Comment by SeptiyanAndika** [comment]
thanks @HyperBrain , for custom authorizer i use this
https://github.com/awslabs/aws-serverless-auth-reference-app/blob/master/api/lambda/authorizer.js

**Comment by HyperBrain** [comment]
Just isolated the issue. It is caused by:
```
authorizer:
  arn: arn:aws:cognito-idp:us-west-2:xxxxx:userpool/us-west-xxxx
```
The plugin should ignore User Pools authorizers and pass them unchanged. Working on a fix.
