### ISSUE TITLE
Error when creating aliases with "-" in the name

### ISSUE THREAD

**Issue by arabold** [HyperBrain/serverless-aws-alias#68]
I've tried to deploy a new alias called "my-test" using `sls deploy --alias my-test`. Unfortunately this fails with an exception:

```bash
  The CloudFormation template is invalid: Template format error: Resource name IamRoleLambdaExecutionmy-test is non alphanumeric.
```

The alias stack is still created and not cleaned up properly. I suggest to simply use camel casing when appending the alias name to CloudFormation resources. That would fix this while still allowing non alphanumeric characters in the alias name itself.

**Comment by HyperBrain** [comment]
I will use normalized alias names internally. The dashes have to be replaced by `Dash` (others too) to eliminate disambiguities like `my-test` and `my--test` which would lead to the same `myTest` if using a common camel case transform like `_.camelCase()`.

**Comment by mbruning24** [comment]
Any update on when this might be added in? Our team would love to tie this into our automated deployment (we tag our assets based on JIRA story key, which contains dashes!). Love this plugin so far.

**Comment by HyperBrain** [comment]
@mbruning24 Sorry, that there wasn't any progress on that yet. I was quite busy with `serverless-webpack` which I ... suddenly ... took over.

Adding this should not be much efforts if it is only done for the rule name, and only if it contains disallowed characters (which is a fixed set) to stay backwards compatible.
I think I can have a look this weekend.

**Comment by HyperBrain** [comment]
Released with 1.5.1

**Comment by piether** [comment]
FYI, this issue is mentioned as "Support _ - + in alias names #68" in the README, but only hyphens work. If I try to use a + or _ I get 
`The stack alias name "..." is not valid. A service name should only contain alphanumeric (case sensitive) and hyphens. It should start with an alphabetic character and shouldn't exceed 128 characters.`

**Comment by chosme** [comment]
Any update on the above mentioned query.
I get an error if I use "_" 
The stack alias name "..." is not valid. A service name should only contain alphanumeric (case sensitive) and hyphens. It should start with an alphabetic character and shouldn't exceed 128 characters.

**Comment by Enase** [comment]
@chosme could you provide `serverless.yml` example?
