### ISSUE TITLE
URL output format

### ISSUE THREAD

**Issue by xavicolomer** [HyperBrain/serverless-aws-alias#70]
Hi there,

I intend to use this plugin for versioning purposes:

Master
`serverless --stage dev`

Versions
`serverless --stage dev --alias v1`

`serverless --stage dev --alias v2`

Endpoints
`https://{{domain}}.execute-api.eu-west-1.amazonaws.com/{{alias}}/resource`

My question is, can I customize the alias format so it becomes with the plugin?
`https://{{domain}}.execute-api.eu-west-1.amazonaws.com/api/{{alias}}/resource`

Note the **/api/** before the {{alias}}

 @Thanks!

**Comment by HyperBrain** [comment]
As the alias is technically an API Gateway Stage, the way to achieve your layout is, to add a custom domain mapping to your APIG API.

Select "Custom domain names" in the AWS APIG console. Then add an URL mapping (e.g. custom domain `mysvc.domain.com` and configure a path like this: `/api -> your-api:*`.

Then you can access the different aliases as: `mysvc.domain.com/api/<alias>/resource...`

**Comment by xavicolomer** [comment]
ok, sounds like a plan.

Do you think its a good idea to use it for versioning?

**Comment by HyperBrain** [comment]
You can try. We use it currently at work for developer branch deployments, but using it for versioning also sounds good. Please give it a try and let me know if it works for that use case. Maybe I cann add this use case to the README later.

**Comment by xavicolomer** [comment]
Ok.

I also need something like this, I'd like to hear some opinions :)
https://github.com/serverless/plugins/issues/79

Thanks for your time
