### ISSUE TITLE
Conditionally running master alias if it has not been run

### ISSUE THREAD

**Issue by justinffs** [HyperBrain/serverless-aws-alias#78]
Awesome plugin and thank you for all the work.  I just have a question if there is a way to check if the initial master alias exists already and if it doesn't then run it.   The reason I am asking is we are planning on setting up a 'stage' per developer then each feature branch the make as an alias.  

Running it once manually for each developer isn't a big deal but it would be nice if it was automated in some way.

**Comment by justinffs** [comment]
`aws apigateway get-rest-apis` will return a list of the APIG deployed so we will use that.  Thanks.

**Comment by HyperBrain** [comment]
@justinffs Thanks for the feedback. If there is anything else that could be improved in the plugin, just let me know.
