### ISSUE TITLE
serverless logs not logging the correct version after serverless deploy function 

### ISSUE THREAD

**Issue by rklhui** [HyperBrain/serverless-aws-alias#89]
The alias of cloudformation stack file is not updated to the latest version after serverless deploy function with alias, leading to serverless logs with alias still displaying the old version of the alias. I guessed either having the --version=latest or --version=xx on serverless logs could solve the problem without updating the cloudformation stack (as this is kind of counter-intuitive).

**Comment by HyperBrain** [comment]
Hi @rklhui , good catch. However, I would prefer the "version" variant, as latest is a floating label, that can easily be wrong as soon as someone else deploys his alias.

**Comment by rklhui** [comment]
Hey @HyperBrain, please see if this  #helps.
#90

**Comment by HyperBrain** [comment]
@rklhui Thanks 😄 . I already added a few comments to the PR and will test it this weekend.
